"""
Maya's X (Twitter) post scheduler.
Run this separately from the main server:
    python scheduler.py

It posts as Maya on a random schedule to feel organic.
Posts are generated by calling Maya's own LLM with a
"post something" prompt — so they stay in character.
"""
import time
import random
import requests
from app.config import MODELSLAB_API_KEY, MODELSLAB_API_URL, MODELSLAB_MODEL
from app.services.x_service import post_tweet
from app.ai.persona import load_persona

# How often to post — random interval between these two values (in seconds)
MIN_INTERVAL = 3 * 60 * 60   # 3 hours
MAX_INTERVAL = 8 * 60 * 60   # 8 hours

POST_PROMPTS = [
    "Write one short tweet as Maya. Something real, a little edgy, about your day in Tahoe. No hashtags. Under 240 characters.",
    "Write one short tweet as Maya about snowboarding or the mountain. Authentic, lowercase, 1-2 sentences. No hashtags.",
    "Write one short tweet as Maya. Flirty but not desperate. Something you'd say at the bar. Under 200 characters.",
    "Write one short tweet as Maya about something she finds annoying or funny. Short, real, lowercase.",
    "Write one short tweet as Maya. Mysterious, a little provocative. Don't explain yourself. Under 180 characters.",
]


def generate_post() -> str:
    persona = load_persona()
    prompt  = random.choice(POST_PROMPTS)

    messages = [
        {"role": "system", "content": persona},
        {"role": "user",   "content": prompt},
    ]

    payload = {"model": MODELSLAB_MODEL, "messages": messages}
    headers = {
        "Authorization": f"Bearer {MODELSLAB_API_KEY}",
        "Content-Type":  "application/json",
    }

    r    = requests.post(MODELSLAB_API_URL, json=payload, headers=headers, timeout=60)
    data = r.json()

    if "choices" in data:
        return data["choices"][0]["message"]["content"].strip()
    elif "output" in data:
        return data["output"][0].strip()

    raise ValueError(f"Unexpected response: {data}")


def run():
    print("Maya scheduler started. Posting to X on a random schedule.")
    while True:
        wait = random.randint(MIN_INTERVAL, MAX_INTERVAL)
        print(f"Next post in {wait // 3600:.1f} hours...")
        time.sleep(wait)

        try:
            text   = generate_post()
            result = post_tweet(text)
            print(f"Posted: {result['text']}")
        except Exception as e:
            print(f"Post failed: {e}")


if __name__ == "__main__":
    run()
